prefix              = "joco" # Prefix for the resources -- max two letters
project             = "job-copilot"
project_number      = "696820564091"
region              = "europe-west1"
location            = "EU"
envname             = "dev"
run_version         = "0.0.8"
run_service_name    = "job-copilot"
secret_file_path    = "../secret.txt"
